---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/proponents/list":
    get:
      summary: list proponent
      tags:
      - Proponents
      parameters:
      - name: page
        in: query
        description: pagination
        schema:
          type: integer
      - name: per_page
        in: query
        description: pagination
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/v1/discount_amount/{amount}":
    parameters:
    - name: amount
      in: path
      description: amount
      required: true
      schema:
        type: string
    get:
      summary: discount_amount proponent
      tags:
      - Discount Amount
      responses:
        '200':
          description: successful
  "/v1/proponents/report":
    get:
      summary: report
      tags:
      - Proponents
      responses:
        '200':
          description: successful
  "/v1/proponents":
    post:
      summary: create proponent
      tags:
      - Proponents
      parameters: []
      responses:
        '422':
          description: invalid params
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                taxpayer_number:
                  type: integer
                birthdate:
                  type: number
                  required: true
                amount:
                  type: number
                  required: true
                contacts_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      number:
                        type: string
                  required:
                  - number
                addresses_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      address:
                        type: string
                      number:
                        type: string
                      district:
                        type: string
                      city:
                        type: string
                      state:
                        type: string
                      zip:
                        type: string
                  required:
                  - address
                  - number
                  - district
                  - city
                  - state
                  - zip
              required:
              - name
              - taxpayer_number
              - birthdate
              - amount
  "/v1/proponents/{id}/update_amount":
    patch:
      summary: update proponent amount
      tags:
      - Proponents
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '422':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
              required:
              - amount
  "/v1/proponents/{id}":
    get:
      summary: show proponent
      tags:
      - Proponents
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '404':
          description: not found
        '200':
          description: successful
    put:
      summary: update proponent
      tags:
      - Proponents
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '404':
          description: not found
        '422':
          description: invalid params
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                birthdate:
                  type: number
                  required: true
                contacts_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      number:
                        type: string
                  required:
                  - number
                addresses_attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      address:
                        type: string
                      number:
                        type: string
                      district:
                        type: string
                      city:
                        type: string
                      state:
                        type: string
                      zip:
                        type: string
                  required:
                  - address
                  - number
                  - district
                  - city
                  - state
                  - zip
              required:
              - name
              - taxpayer_number
              - birthdate
              - amount
    delete:
      summary: delete proponent
      tags:
      - Proponents
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '404':
          description: successful
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
